### ISSUE TITLE
install with docker image

### ISSUE THREAD

**Issue by nujcharee** [VROOM-Project/vroom-docker#8]
Hello there, 
I am new to docker and vroom so hope you could help guide me please?
I got osrm backend installed locally, I would like to use optimisation for vehicle routing problem. 
Do i need to install open route service locally to do this or OSRM should do the job?

These are the steps I already took

1. Successfully installed OSRM locally via docker
2.  Clone this repo
3. Run this command docker-compose -f docker-compose.yml up
then I received this error
ERROR: manifest for openrouteservice/openrouteservice:6.0.1 not found: manifest unknown: manifest unknown

I must have missed something - please could you kindly guide me what I need to do?
Thank you so much
Ped

**Comment by nilsnolde** [comment]
ORS or OSRM is up to you, both do the job. You'll have to use the `

Uncomment the not wanted router in the `docker-compose.yml`. In case of OSRM, you **only** need to `docker-compose up -d` and the appropriate commands for OSRM (look at their dockerhub page). You don't have to run OSRM in a separate container. In case of ORS, you actually can't use the dockerhub hosted version, so you'd need to clone ORS and build the image yourself. Then reference that in the `docker-compose.yml` (e.g. `openrouteservice/openrouteservice:6.0.1`, as the default). This is not well documented actually, that's true. That's because I'd like to change the ORS image a little too, so it can be used from dockerhub. Will do that soon.

**Comment by nilsnolde** [comment]
Accidentally closed, but wanted to close anyways. You can still get back to us if there's some problems with this repository.

**Comment by nujcharee** [comment]
Thank you for help. What I’m not clear is, if I want to solve TSP problem I suppose I need to use ORS rather then OSRM is that right? I’m happier with OSRM as I managed to get it working but struggling on ORS. My main goal is to plan jobs with constraints.
Hope you can advice thank you much this is really helpful :)

**Comment by jcoupey** [comment]
The optimization (TSP or other flavour of vehicle routing problem) happens inside `vroom` (see [backend repo](https://github.com/VROOM-Project/vroom)). But the optimization layer has to work on top of some "routing layer" to retrieve travel times from/to locations in the problem.

Now both OSRM and ORS are supported out of the box and either one will do the job (you don't need both). Which one you pick is totally up to you, rather a matter of taste.
